name: Run Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Playwright Test Matrix
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    strategy:
      matrix:
        suite: [
          test:auth-only,
        #   test:products-only,
        #   test:contact-only,
        #   test:smoke-suite
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Install Playwright browsers with retry
        run: |
          for i in 1 2 3; do
            echo "Attempt $i to install browsers..."
            npx playwright install --with-deps && break || sleep 5
          done

      - name: 'Run Playwright suite: ${{ matrix.suite }}'
        run: npm run ${{ matrix.suite }}

    #   - name: Upload Playwright HTML Report
    #     if: always()
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: playwright-report-${{ matrix.suite }}
    #       path: playwright-report
