name: Playwright Test Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-playwright-suites:
    runs-on: ubuntu-22.04  # ✅ FIX: use supported OS

    strategy:
      matrix:
        suite: [test:auth-only, test:products-only, test:contact-only]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps  # ✅ RECOMMENDED instead of deprecated action

      - name: Run Playwright test suite (${{ matrix.suite }})
        run: npm run ${{ matrix.suite }}

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.suite }}
          path: playwright-report
