name: Playwright Matrix Test Suites

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [test:auth-only]
        # test:products-only, test:contact-only]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Suite - ${{ matrix.suite }}
        run: npm run ${{ matrix.suite }}

      - name: Upload Playwright Report - ${{ matrix.suite }}
        if: always()  # ensure report is uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.suite }}-report
          path: playwright-report
